### ISSUE TITLE
Attribute support?

### ISSUE THREAD

**Issue by saethlin** [aldanor/hdf5-rust#32]
I would _really_ like to use this crate but all my usage of HDF5 requires pulling metadata out of attributes. I'm willing to contribute (to) attribute support if you can offer me some direction.

**Comment by aldanor** [comment]
@saethlin Hey, cheers and thanks for interest in the crate.

I'm working on this crate in "waves", so to speak, when I'm free for a few weeks inbetween other projects, trying to do as much as possible in as little time as is available :) Hoping to start the new batch of work on this sometime this month, main priorities being reworking file builders, making use of the new implemented fapl/fcpl APIs, and reworking dataset builders. Plus, we finally need to release this to crates.io.

As for attributes - that's certainly the next thing on the todo list since quite a few people asked for it. As a matter of fact, the Container API already supports reading/writing to/from attributes. You could say that the hard part is already done. One just needs to implement the Attribute type and attribute indexing, retrieval and creation from any Location, so you could then do things like `dataset.attr("foo")?.read_scalar::<i64>()`.

If you wanted to try and contribute without waiting, I'd say browse around [H5A docs](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5A.html), [ACPL docs](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#AttributeCreatePropFuncs) (there's actually only one property), and as a (not so perfect since I'm itching to refactor it) reference - the current [Dataset](https://github.com/aldanor/hdf5-rs/blob/master/src/hl/dataset.rs) implementation as a high-level type, ignoring all dataset-specific stuff. You should probably be quite comfortable with both the HDF5 C library and Rust in order to write it all by yourself.

Otherwise, I could try tackling it myself; what could help is this: typical usage patterns, i.e. how attributes are typically created and accessed, checked, iterated over etc; in all my years with HDF5 I haven't had any use out of them so I only have a vague general idea (despite the fact that I'm familiar with H5A API quite well).

**Comment by saethlin** [comment]
I'm somewhat familiar with H5A already, having done a bit of HDF5 work through C (though most of my work is through h5py). I'll familiarize myself with the Container API soon, thanks for the direction.

In terms of API, I've only ever used attributes as a key-value store for units and other such metadata, such as the parameters that a simulation was run with. The only use I've ever found for iterating over attributes is to answer "What attributes does this thing have?" without leaving a Python interpreter, which is honestly the job of a good `Debug` impl.

**Comment by aldanor** [comment]
> which is honestly the job of a good `Debug` impl

That is.. until you have thousands of attributes :) I think I'd rather have something like `<Dataset "foo": int64, 10x10, 5 attributes>`, and then `dataset.ls()` or `hdf5::ls()` which would do something like what h5dump does.

> I'll familiarize myself with the Container API soon, thanks for the direction.

Just to repeat myself, I *think* the Container API would work with H5A (it has H5A calls), but we've never checked. I wouldn't see a reason why it wouldn't (but you'll have to write tests...). Which means you just need to make the Attribute object Deref-able to it (just like Dataset does it), and that's it. The rest is H5A-specific stuff, like querying attributes, iterating over them, or creating new ones.

I'll also try to collect contributors guidelines in one place and check it in, so that this information is not scattered across various issues and pull requests - which will hopefully make it easier.

**Comment by TheQuantumPhysicist** [comment]
@aldanor 
Given that attributes are still inaccessible with the library, I was trying to invent my own solution yesterday by adding temporary `extern "C"` to my code with `H5Aopen` and similar that I could remove later when attributes are supported. That, however, was not possible because `hid_t` is completely private and I couldn't access it by just importing the package. The more I tried to do this, the more code I had to copy from internals to make this possible, so I eventually stopped.

I'm not sure what I'm here since I don't understand the library's internals fully, but can we either make internal elements that can allow users to implement their own extensions (such as hid_t and others) public, or show the timeline of supporting attributes? I was completely blocked because of this.

I would've happily contributed and implemented this myself, but I'm still new to rust (a couple months), and I don't feel I'm qualified to contribute yet. In fact, I'm writing this project in rust to learn more.

**Comment by aldanor** [comment]
@TheQuantumPhysicist apologies for delays, it's just I'm finishing humongous branch right now (many thousands lines) so I can't do this all at once.

Re: internals, it's all completely public and not hidden at all! You don't have to write any `extern "C"` blocks either, **full** bindings are available in `hdf5-sys` crate. Which means you can always just

```rust
let foo: hid_t = 1;
unsafe { H5Aopen(...); }
```

**Comment by TheQuantumPhysicist** [comment]
@aldanor 
No worries. I'm happy to write my own C extensions to get my little project going (I'm a C++ person originally). It's just that my ignorance in Rust is playing against me at times.

Thank you for the information. I'll try this and provide feedback if it's valuable.

**Comment by TheQuantumPhysicist** [comment]
@aldanor 
It doesn't seem to be possible to use `hid_t`. Allow me explain why and what I'm seeing.

I have this added in my `Cargo.toml`: `hdf5 = { git = "https://github.com/aldanor/hdf5-rust" }`, so I have the latest version of hdf5.

In that, the only place where `hdf5_sys` is kind of reachable in the file `lib.rs` in the root of the source is: 
```
mod internal_prelude {
//...
    pub use hdf5_sys::{
//...
```
Notice that `internal_prelude` is not public. So `hdf5_sys` is not reachable, and hence, `hid_t` is not reachable.

Is there a way to circumvent this?

**Comment by aldanor** [comment]
@TheQuantumPhysicist Of course. Just add `hdf5-sys` to your dependencies and use `hdf5_sys::h5i::hid_t`. It's a standalone crate and it doesn't depend on anything (except the hdf5 C library itself).

**Comment by TheQuantumPhysicist** [comment]
@aldanor 
Is there a way to do this from the repo without having to copy stuff manually? This:
```
extern crate hdf5_sys;
```
Combined with `Cargo.toml`'s:
```
hdf5-sys = { git = "https://github.com/aldanor/hdf5-rust" }
```
Doesn't work because the crate name has a dash `-`, while that cannot be in the package name.

**Comment by kylegalloway** [comment]
Will this be coming anytime soon? I want to use Rust for a project that reads hdf5, but I can't use it if I can't read attributes. I don't need anything fancy. Something like the following would be fine:

`let my_attrs = file.dataset("my_dataset")?.attributes()`

Or individual access like

`let my_attr = file.dataset("my_dataset")?.attribute::<f64>("my_attr")`

**Comment by gauteh** [comment]
Is it possible to get the `hid_t` from an already open `hdf5::File`? Or do I have to open a new one using   `hdf5_sys`? Maybe it would be possible to add a getter to the `hid` field, possibly guarded by `unsafe`?

**Comment by balintbalazs** [comment]
PR #65 by @pmarks works for me also on top of the master branch with a minor modification: https://github.com/balintbalazs/hdf5-rust/tree/attrs. Using that you don't need to worry about the `hdf5_sys` calls. You can find some examples in the tests: https://github.com/balintbalazs/hdf5-rust/blob/da40301f81252570f1973996a50b86967250a979/src/hl/attribute.rs#L166

**Comment by gauteh** [comment]
Thanks @balintbalazs, I'll try your modified version.
