### ISSUE TITLE
Is it possible to iterate over all datasets/attributes?

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [aldanor/hdf5-rust#46]
I'm looking in the [docs](https://aldanor.github.io/hdf5-rust/hdf5/index.html) and I can't find anything to do that. Is it not possible still?

**Comment by jbabyhacker** [comment]
I just put up a PR #53 for part of the feature you are looking for.

**Comment by TheQuantumPhysicist** [comment]
@jbabyhacker Thanks, this sounds great. 

Although I found a much bigger problem, because of which I had to stop my project and give up on HDF5 with rust for now. There doesn't seem to be a way to access attributes at all. Only datasets access is possible.

**Comment by aldanor** [comment]
@TheQuantumPhysicist attributes are next/current thing on a list - first the dataset/datasetbuilder/filters API needs to be cleaned up and refactored which is currently being done (DAPL done already, DCPL + filters on the way).

The attributes themselves should be fairly trivial then; the current Reader/Writer API already supports attributes so that part should work automatically. I'll keep you posted.

**Comment by aldanor** [comment]
#53 with member iteration has been merged; closing this in favour of #32 (attribute support).
